Acme.Web/ViewModels/PersonEmployeeVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Acme.Web.ViewModels
{
    public class PersonEmployeeVm
    {
        [Display( Name = "First Name" )]
        [StringLength( 128 )]
        public string FirstName { get; set; }

        [Display( Name = "Last Name" )]
        [StringLength( 128 )]
        public string LastName { get; set; }

        [Display( Name = "Birth Date" )]
        [DataType( DataType.Date, ErrorMessage = "Please enter a valid date in the format dd/mm/yyyy" )]
        public DateTime BirthDate { get; set; }

        [Display( Name = "Employee No." )]
        [StringLength( 16 )]
        public string EmployeeNum { get; set; }

        [Display( Name = "Employed Date" )]
        [DataType( DataType.Date, ErrorMessage = "Please enter a valid date in the format dd/mm/yyyy" )]
        public DateTime EmployedDate { get; set; }

        [Display( Name = "Terminated Date" )]
        [DataType( DataType.Date, ErrorMessage = "Please enter a valid date in the format dd/mm/yyyy" )]
        public DateTime? TerminatedDate { get; set; }
    }
}

Acme.Web/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Acme.Services.Client;
using Acme.Services.Dto;
using Acme.Web.ViewModels;

namespace Acme.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IWebServiceClient<EmployeeDto> _client;

        public EmployeeController() : this( new WebServiceClient<EmployeeDto>()) {}

        public EmployeeController( IWebServiceClient<EmployeeDto> client )
        {
            _client = client;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var employees = await _client.GetAllAsync();

            return View( employees );
        }

        [HttpGet]
        public ActionResult Create()
        {            
           return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create( [Bind( Include = "FirstName,LastName,BirthDate,EmployeeNum,EmployedDate,TerminatedDate" )] PersonEmployeeVm model )
        {
            if ( ModelState.IsValid )
            {
                EmployeeDto dto = new EmployeeDto();
                dto.Person.FirstName = model.FirstName;
                dto.Person.LastName = model.LastName;
                dto.Person.BirthDate = model.BirthDate;
                dto.EmployeeNum = model.EmployeeNum;
                dto.EmployedDate = model.EmployedDate;
                dto.TerminatedDate = model.TerminatedDate;

                OperationResult op = await _client.AddAsync( dto );

                if ( !op.Success ) 
                {
                    ModelState.AddModelError( "", "Problem creating" );
                    return View( model );
                }

                return RedirectToAction( "Index" );
            }

            return View( model  );
        }

    }
}

Acme.Web/Views/Employee/Create.cshtml
@model Acme.Web.ViewModels.PersonEmployeeVm


@using ( Html.BeginForm() )
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PersonEmployeeVm</h4>
        <hr />
        @Html.ValidationSummary( true, "", new { @class = "text-danger" } )
        <div class="form-group">
            @Html.LabelFor( model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor( model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor( model => model.FirstName, "", new { @class = "text-danger" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor( model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor( model => model.LastName, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor( model => model.LastName, "", new { @class = "text-danger" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor( model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor( model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor( model => model.BirthDate, "", new { @class = "text-danger" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor( model => model.EmployeeNum, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor( model => model.EmployeeNum, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor( model => model.EmployeeNum, "", new { @class = "text-danger" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor( model => model.EmployedDate, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor( model => model.EmployedDate, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor( model => model.EmployedDate, "", new { @class = "text-danger" } )
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor( model => model.TerminatedDate, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor( model => model.TerminatedDate, new { htmlAttributes = new { @class = "form-control" } } )
                @Html.ValidationMessageFor( model => model.TerminatedDate, "", new { @class = "text-danger" } )
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink( "Back to List", "Index" )
</div>

Acme.Web/Views/Employee/Index.cshtml
@model IEnumerable<Acme.Services.Dto.EmployeeDto>


<p>
    @Html.ActionLink( "Create New", "Create" )
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor( model => model.Person.FirstName )
        </th>
        <th>
            @Html.DisplayNameFor( model => model.Person.LastName )
        </th>
        <th>
            @Html.DisplayNameFor( model => model.Person.BirthDate )
        </th>
        <th>
            @Html.DisplayNameFor( model => model.EmployeeNum )
        </th>
        <th>
            @Html.DisplayNameFor( model => model.EmployedDate )
        </th>
        <th>
            @Html.DisplayNameFor( model => model.TerminatedDate )
        </th>
        <th></th>
    </tr>

    @foreach ( var item in Model )
    {
        <tr>
            <td>
                @Html.DisplayFor( model => item.Person.FirstName )
            </td>
            <td>
                @Html.DisplayFor( model => item.Person.LastName )
            </td>
            <td>
                @Html.DisplayFor( model => item.Person.BirthDate )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.EmployeeNum )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.EmployedDate )
            </td>
            <td>
                @Html.DisplayFor( modelItem => item.TerminatedDate )
            </td>
            <td>
                @Html.ActionLink( "Edit", "Edit", new { id = item.Id } ) |
                @Html.ActionLink( "Details", "Details", new { id = item.Id } ) |
                @Html.ActionLink( "Delete", "Delete", new { id = item.Id } )
            </td>
        </tr>
    }

</table>

Acme.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Acme.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Acme.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Acme.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render( "~/Content/css" )
    @Scripts.Render( "~/bundles/modernizr" )

    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink( "Application name", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" } )
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render( "~/bundles/jquery" )
    @Scripts.Render( "~/bundles/bootstrap" )
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    @RenderSection( "scripts", required: false )
</body>
</html>